# Generated by Django 3.0.5 on 2021-11-23 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ingredient name')),
                ('measurement_uint', models.CharField(max_length=200, verbose_name='Measurement unit')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientPortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Portion size')),
            ],
        ),
        migrations.CreateModel(
            name='IsFavorited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IsInShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Recipe name')),
                ('image', models.ImageField(upload_to='', verbose_name='Recipe image')),
                ('text', models.CharField(max_length=1000, verbose_name='Recipe description')),
                ('cooking_time', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Recipe cooking time, minutes')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Recipe publication date')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Tag name')),
                ('color', models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Tag color')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Tag slug')),
            ],
        ),
    ]
