# Generated by Django 3.0.5 on 2021-11-23 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Recipe author'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe.IngredientPortion', to='recipe.Ingredient', verbose_name='Ingredients with a portion'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(db_index=True, to='recipe.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='isinshoppingcart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_cart_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='isinshoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='recipe.Recipe', verbose_name='Favorited recipe'),
        ),
        migrations.AddField(
            model_name='isfavorited',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Follower'),
        ),
        migrations.AddField(
            model_name='isfavorited',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='recipe.Recipe', verbose_name='Favorited recipe'),
        ),
        migrations.AddField(
            model_name='ingredientportion',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portion', to='recipe.Ingredient', verbose_name='Ingredient in portion'),
        ),
        migrations.AddField(
            model_name='ingredientportion',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_portion', to='recipe.Recipe', verbose_name='Recipe with portion'),
        ),
        migrations.AddConstraint(
            model_name='isinshoppingcart',
            constraint=models.UniqueConstraint(fields=('customer', 'recipe'), name='unique_in_cart_pair'),
        ),
        migrations.AddConstraint(
            model_name='isfavorited',
            constraint=models.UniqueConstraint(fields=('follower', 'recipe'), name='unique_favorited_pair'),
        ),
    ]
