# Generated by Django 2.2.6 on 2021-12-12 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='ingredientportion',
            options={'verbose_name': 'Portion', 'verbose_name_plural': 'Portions'},
        ),
        migrations.AlterModelOptions(
            name='isfavorited',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='isinshoppingcart',
            options={'verbose_name': 'Shopping cart', 'verbose_name_plural': 'Shopping carts'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveConstraint(
            model_name='isfavorited',
            name='unique_favorited_pair',
        ),
        migrations.RemoveConstraint(
            model_name='isinshoppingcart',
            name='unique_in_cart_pair',
        ),
        migrations.RenameField(
            model_name='isfavorited',
            old_name='follower',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='isinshoppingcart',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ingredientportion',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Amount can not be less than 1.')], verbose_name='Portion size'),
        ),
        migrations.AlterField(
            model_name='isinshoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='recipe.Recipe', verbose_name='Recipe in cart'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Cooking time can not be less than 1 minute.')], verbose_name='Recipe cooking time, minutes'),
        ),
        migrations.AddConstraint(
            model_name='ingredientportion',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_portion_pair'),
        ),
        migrations.AddConstraint(
            model_name='isfavorited',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorited_pair'),
        ),
        migrations.AddConstraint(
            model_name='isinshoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_in_cart_pair'),
        ),
    ]
