# Generated by Django 2.2.6 on 2021-12-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement_uint',
            new_name='measurement_unit',
        ),
    ]
