# Generated by Django 2.2.6 on 2021-12-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20211123_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientportion',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='recipe.Ingredient', verbose_name='Ingredient in portion'),
        ),
        migrations.AlterField(
            model_name='ingredientportion',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_in_portion', to='recipe.Recipe', verbose_name='Recipe with portion'),
        ),
    ]
